services:
  pi_inference:
    image: pi_inference:${USER}
    build:
      context: .
      dockerfile: Dockerfile.cuda
    container_name: pi_inference-${USER}
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../fr3_pi_inference:/home/user/pi_inference
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/udev/rules.d:/etc/udev/rules.d
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
